### ISSUE TITLE
Add Jboss/Wildfly JMX remote protocol support

### ISSUE THREAD

**Issue by AlexDeAg** [open-telemetry/opentelemetry-java-contrib#1087]
### Component(s)

jmx-metrics

### Is your feature request related to a problem? Please describe.

We are having issues collecting metrics from JBoss 6+/Wildfly 10+. The current receiver only supports the RMI protocol for the jmx_url, which has been deprecated since version 6 of JBoss.

### Describe the solution you'd like

The solution could be to also add support for the JBoss Remote Protocol service:jmx:remote+http://<IP_Address>:port

**Comment by trask** [comment]
(not sure why github isn't letting me add @rmfitzpatrick as an assignee 🤔)

**Comment by dehaansa** [comment]
Support for the remote+http protocol requires adding the relevant jboss-client.jar file from your wildfly/jboss installation to the classpath when you run the JMX Metrics Gatherer. This behavior is how wildfly/jboss collection is supported inside the [Contrib Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/jmxreceiver#additional_jars), so it's been validated in that context.

Due to licensing & legal reasons, the jboss-client/remote protocol cannot be packaged with the JMX Metrics Gatherer.

**Comment by dehaansa** [comment]
1. I don't think we have a list of supported protocols available. I am personally only aware of support for RMI and remote+http for wildfly.

2. By default the logging is somewhat limited. If you'd like more detailed logging use the `-Dorg.slf4j.simpleLogger.defaultLogLevel=debug` system property when running the receiver.  Logs should be written to `stderr` by default, according to the docs you could write to a file using another system property `-Dorg.slf4j.simpleLogger.logFile=/log/location/` but I have not personally tested that.

**Comment by rmfitzpatrick** [comment]
Considering the metric gatherer will transparently forward the `otel.jmx.service.url` value to construct a `javax.management.remote.JMXServiceURL` to establish a connection, and that it's up to each target to establish their supported protocol, I don't believe any changes are necessary for this issue.
