### ISSUE TITLE
X-Ray Remote Sampler does not poll for new rules

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-java-contrib#133]
**Description**
Currently, the X-Ray sampler only polls the `GetSamplingRules` once on startup: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/b5d88e223c8c316b5d97474e5d2ff8fc4b428af1/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/XraySamplerClient.java#L62

This is problematic because if a customer creates a new sampling rule, it will never be picked up by the application until it is redeployed.

**Steps to reproduce**
1. Create a sample app using the X-Ray Remote Sampler
2. Run the application
3. Create a new sampling rule on the AWS Console
4. Observe that the new sampling rule is never picked up by the app

**Expectation**
Instead, the remote sampler should poll the `GetSamplingRules` API periodically, every 5 minutes.

cc @anuraaga

**Comment by anuraaga** [comment]
The relevant code is here which does reschedule.

https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayRemoteSampler.java#L147

I know @wangzlei saw some behavior that indicated this may not be happening but just wondering if you were able to confirm the repro steps? During initial testing I could confirm dynamic update of the rules and code hasn't changed since so wondering if it's a corner case

**Comment by willarmiros** [comment]
I have not confirmed the repro steps, and I wasn't looking at that code which does look good. Maybe @wangzlei can either provide a repro or enable `FINE` level logs to see if some weird exception is occurring?
