### ISSUE TITLE
JMX receiver jar relies on setting otel.imr.export.interval

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java-contrib#153]
See: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/src/main/groovy/io/opentelemetry/contrib/jmxmetrics/JmxConfig.java#L23

We should have some kind of unit tests to make sure the pass-through enviornment variables line up.  This breaks using the JMX receiver using collector-contrib configuration.

**Comment by rmfitzpatrick** [comment]
@jsuereth are you reporting that the `otel.jmx.interval.milliseconds` and `otel.imr.export.interval` are separate properties and should be unified? The first determines the groovy script running interval and the other is for the exporter. The JMX receiver could be updated to set both with the collection interval but I'm not immediately seeing another problem.

**Comment by sophieyfang** [comment]
@rmfitzpatrick We are seeing the collection_interval not being respected, the streams are generated at a frequency that's often < 10s causing a problem in our side. (Points get denied by API side if it's being written too fast)

**Comment by sophieyfang** [comment]
> @jsuereth are you reporting that* `otel.jmx.interval.milliseconds` and `otel.imr.export.interval` are separate properties and should be unified? The first determines the groovy script running interval and the other is for the exporter. The JMX receiver could be updated to set both with the collection interval but I'm not immediately seeing another problem.

I think Josh meant [otel.imr.export.interval](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/v1.9.0/jmx-metrics/src/main/groovy/io/opentelemetry/contrib/jmxmetrics/JmxConfig.java#L23) and [otel.metric.export.interval](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java#L158)?

**Comment by cpheps** [comment]
So I've been researching this a bit. It appears that [otel.imr.export.interval](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/v1.9.0/jmx-metrics/src/main/groovy/io/opentelemetry/contrib/jmxmetrics/JmxConfig.java#L23) has been deprecated since 1.9.0 according to the [opentelemetry-java changelog](https://github.com/open-telemetry/opentelemetry-java/blob/main/CHANGELOG.md?plain=1#L168-L170). 

Unless I'm missing some code flow this would mean the JMX config is setting the old property for export interval rather than the new one. Since the value is never set it looks like it defaults to [1 minute](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java#L158-L161).

I think this is what @jsuereth was getting at originally. I'm not sure if this will fix what @sophieyfang is seeing as far as the generated frequency being <10s that requires further investigation.

**Comment by cpheps** [comment]
I'm submitting a PR to fix the deprecate exporter interval value. In testing though it seems like that interval may not be respected fully. I need to look into it further and will create a follow up PR if needed.

**Comment by cpheps** [comment]
I closed my PR I missed that `otel.imr.export.interval` still has backwards compatibility support in [1.9.1](https://github.com/open-telemetry/opentelemetry-java/blob/v1.9.1/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java#L155-L161) which is what's in `main`.

That being said I setup a debugger on a running jmx receiver that is configured via collector-contrib. I confirmed that the interval value is being passed all the way down to the thread scheduler [here](https://github.com/open-telemetry/opentelemetry-java/blob/v1.9.1/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java#L103-L112). 

I'm not sure there is an issue with setting the exporter interval as far as I can tell but going to continue investigating to see if I can figure find the issue @sophieyfang is seeing.

**Comment by cpheps** [comment]
Ok I found out what is causing the appearance that the jmx collector is collecting more often than it is. I'm still not sure 100% of how it's happening but on every execution of the groovy script in JMX jar it [flushes](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/src/main/groovy/io/opentelemetry/contrib/jmxmetrics/GroovyRunner.java#L134-L139) the exporter to the waiting endpoint. I've observed depending on when the scheduled exporter runs it could execute seconds after a flush (or vice versa) pushing the data multiple times. 

If I comment out the flush and run JMX it exports on the interval specified. I think it has something to do with how the [SdkMetricProvider](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java#L134-L169) and [PeriodicMetricReader](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java#L121-L149) work during an export but I'm not complete sure why a simultaneous flush/export would cause an issue.

@rmfitzpatrick Can you explain the reasoning for the flushing after every run instead of waiting for the exporter to run on its own?

**Comment by rmfitzpatrick** [comment]
@cpheps thanks for tracking this down. The initial functionality of the gatherer would [collect and flush](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/33d89eac42eafb827e24419f5c1e689f7972e7f6/contrib/jmx-metrics/src/main/java/io/opentelemetry/contrib/jmxmetrics/GroovyMetricEnvironment.java#L101) on the runner interval. I don't recall the specific transition point but as the api/sdk evolved we should have stopped managing the MeterProvider directly since its collection and exporting are self managed.

**Comment by cpheps** [comment]
> I don't recall the specific transition point but as the api/sdk evolved we should have stopped managing the MeterProvider directly since its collection and exporting are self managed.

@rmfitzpatrick based on that seems like it would be ok to remove the deliberate flush on the JMX exporter? I might have misunderstood though so looking for some validation.

**Comment by rmfitzpatrick** [comment]
@cpheps I think so, but haven't confirmed locally

**Comment by cpheps** [comment]
@rmfitzpatrick Just following up if you've been able to confirm removing flush is fine. Let me know if theres some tests I can run on my end to do the verification.

**Comment by rmfitzpatrick** [comment]
Newest version 1.10.0 should resolve this issue.
