### ISSUE TITLE
What is the minimum maven version to support for maven-extension and static-instrumenter?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#467]
It looks like `maven-extension` supports 3.5.0+, that seems like a reasonable baseline, and we could update `static-instrumenter` to the same.

**Comment by cyrille-leclerc** [comment]
Thanks @trask,

You are right on the decision for the OTel Maven Extension to pick 3.5.0 rather than the latest MAven Core version available.
We want to support all Maven 3.5.0+ users.

Why did we pick 3.5.0 and not more recent? Here are few elements:
1. We didn't have MAven adoption statistics to help us
2. 3.5.0 was a major bump of Maven with interesting new APIs for Observability so supporting older versions felt not necessary and maybe not possible
3. We didn't identify improvements of Maven Core APIs after 3.5.0 that would enable new observability capabilities

Does it make sense?
