### ISSUE TITLE
AWS X-Ray Centralized Sampler

### ISSUE THREAD

**Issue by luneo7** [open-telemetry/opentelemetry-java-contrib#69]
**Is your feature request related to a problem? Please describe.**
Today we already have a Jaeger remote sampler in the Java SDK, but we don't have one that targets AWS X-Ray, it would be nice to have one sampler for X-Ray.

**Describe the solution you'd like**
A sampler that takes the service name, a fallback sampler, and a endpoint parameter that can point to the X-Ray service or to the X-Ray receiver with proxy server enabled, that fetches the sampling config and does centralized sampling.

**Comment by anuraaga** [comment]
Hi @luneo7 - the Java support is complete, with 1.4 being released to Maven Central for consumption as a library, and the next version of aws-otel-java agent distribution will include it as an option. We are still working on changes to the collector to make the experience simpler - the collector will expose an `awsapiproxy` extension which would authenticate the sampling requests made by the Java code. Before that happens, it will still work hackily, which we don't intend to document since it's too awkward, but the xrayreceiver can be used to proxy sampling requests even if not used for actual trace injection.

https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/awsTest/resources/otel-collector.yml#L2

**Comment by willarmiros** [comment]
Closing this since it's released: https://aws-otel.github.io/docs/getting-started/java-sdk/trace-manual-instr#using-x-ray-remote-sampling
